### ISSUE TITLE
ex-tool-management.md task 13

### ISSUE THREAD

**Issue by annefou** [galaxyproject/dagobah-training#40]
In Task 13 https://github.com/galaxyproject/dagobah-training/blob/2018-oslo/sessions/04-tool-shed/ex-tool-management.md

instead of source activate ~/.venv/bin/activate

we should have

source ~/.venv/bin/activate

**Comment by nsoranzo** [comment]
Fixed in commit https://github.com/galaxyproject/dagobah-training/commit/4a5dc8eb22dd5a56c4af7bad9138f1ac6a7fb00e
