### ISSUE TITLE
Add ephemeris to install a couple tools

### ISSUE THREAD

**Issue by erasche** [galaxyproject/dagobah-training#68]
- using ephemeris and yaml tool files and categories etc.
- How to extract tools.yaml from running Galaxy

**Comment by martenson** [comment]
old ex.: https://github.com/galaxyproject/dagobah-training/blob/2019-pennstate/sessions/04-tool-shed/ex-tool-management.md

**Comment by martenson** [comment]
https://github.com/galaxyproject/training-material/pull/1203

**Comment by erasche** [comment]
Done
