### ISSUE TITLE
VM configuration

### ISSUE THREAD

**Issue by martenson** [galaxyproject/dagobah-training#7]
Please modify as you see fit @natefoo @blankenberg @Slugger70 

- [x] ubuntu 16.04
- [x] [build-essential](http://packages.ubuntu.com/xenial/build-essential)
- [x] git
- [x] vim, nano, emacs
- [x] Ansible
- [x] Python 2.7
- [x] virtualenv
- [x] oracle Java
- [ ] conda
- [x] planemo
- [x] SMTP
- [x] ProFTPD

**Comment by natefoo** [comment]
By "all dev packages" do you mean [build-essential](http://packages.ubuntu.com/xenial/build-essential)?

**Comment by martenson** [comment]
@natefoo I think that is how @blankenberg or @Slugger70 called it. I would expect to be what you linked. Do we need more?

**Comment by natefoo** [comment]
vim/nano/emacs/??

**Comment by martenson** [comment]
@natefoo added

Anything else regarding the VMs? What about config?

What we don't ask for now we have to guide people through during the sessions.

**Comment by Slugger70** [comment]
Oops, we forgot oracle java

**Comment by martenson** [comment]
Conda, Planemo, Homebrew

**Comment by martenson** [comment]
I updated the top post with what I found on the 01 VM

**Comment by natefoo** [comment]
If you're gonna mess with a VM start from the highest number so we can number people off starting with 1. =D

**Comment by martenson** [comment]
I think only the 01 is available atm

**Comment by natefoo** [comment]
Ah ok
